### PR TITLE
Adding gitlab support! 🚀

### LINKED ISSUE #124: Add support to gitlab
I think, it's really helpfull to add support for gitlab server. Since the gitlabs servers are 'private', that is possible by launching David on our servers

### PR DESCRIPTION
**Pull request by gabrielcsapo**
A working version of https://github.com/wzrdtales/david-www/tree/gitlabNew.

screen shot 2017-07-14 at 6 08 12 pm

Thank you @wzrdtales for working on this! 😄 

To test this bring clone down this branch and navigate to `http://localhost:1337/r/gitlab/gitlab-org/gitlab-ce/status.svg`

fixes #124

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
@alanshaw this is working, it just needs a Gitlab personal token to call any of the APIs

**Comment by alanshaw** [comment]
This is kinda cool, my one worry is that I don't have access to a gitlab so I don't know how I'd test, maintain or support this in the future.

@wzrdtales @gabrielcsapo could you explain on a high level how this has been implemented? It looks as though there are separate routes for gitlab. I'm curious to know the reasoning behind that approach as opposed to simply using the existing routes but having a github adapter that calls out to gitlab...

Is the intention that david-dm.org supports gitlab, or just that you can run your own david that can talk to a gitlab?

**Comment by wzrdtales** [comment]
@alanshaw Today such things as access to open source software are easy pie :) 
Here you go https://hub.docker.com/r/gitlab/gitlab-ce/

The reason for the new route is to distinguish between systems. So to have it work with multiple systems at best. Maybe even multiple instances of gitlab, which as far as I remember wasn't implemented though. If you reuse the default routes, you would either need to prioritize either github or gitlab and have an always potentially ambigous state or you would need to give up on one of both though.

**Comment by wzrdtales** [comment]
and the intention is actually the latter one, while the former would be a benefical extension to your service to support gitlab.com which is as github free for everyone. So for the former one this is kinda a decision you need to make for yourself.

**Comment by gabrielcsapo** [comment]
yeah I also saw it as almost a backwards compatible way of moving badges over to this new paradigm.  

@wzrdtales makes a good point with the docker routes, seems like that is an easy way to access services. Could be expanded to incorporate bitbucket also! The way @wzrdtales implemented the routes is really easy to customize and add services as they come available.

**Comment by gabrielcsapo** [comment]
@alanshaw thoughts? Integrating other code providers gives us the ability to leverage a larger community.

**Comment by alanshaw** [comment]
Apologies, I haven't had a moment to look over this yet - please keep bugging me ;)

**Comment by gabrielcsapo** [comment]
🐛 @alanshaw

**Comment by gabrielcsapo** [comment]
I think this PR will make us revisit the server architecture. Which could coincide with a revamp to the UI and functionality.

**Comment by gabrielcsapo** [comment]
🐛 @alanshaw

**Comment by gabrielcsapo** [comment]
🐛 @alanshaw

**Comment by gabrielcsapo** [comment]
@alanshaw thoughts on this?

**Comment by gabrielcsapo** [comment]
:(

**Comment by wzrdtales** [comment]
Don't give up @gabrielcsapo

**Comment by gabrielcsapo** [comment]
I was thinking the functionality that we need should really be built out into something else. In open source fashion if it doesn’t exist build it. David and David-www modules are incredible useful and can be used to be something more geared towards a multi tenet system for npm dependencies.

**Comment by gabrielcsapo** [comment]
Let’s start a conversation about what that would look like https://github.com/gabrielcsapo/helo

**Comment by wzrdtales** [comment]
I'm in :). But don't expect me before next week, I'm currently deep into preparation for DockerCon, I will come back to this topic after that. Don't hesitate to remind me of this in 2 weeks though :)

**Comment by alanshaw** [comment]
So sorry to both of you. I just haven't had a moment to look at this one. We also had sponsorship for a while but the company stopped paying the invoices and didn't tell us they wanted to stop sponsoring the project so they got months of free advertising and they still owe us about £1,000. So I've not even been able to work on david as a paid venture either. I'm sorry but client work to pay the bills and family time in the evening are my priority right now.

**Comment by gabrielcsapo** [comment]
@wzrdtales I will start throwing something together based on this PR and what we talked about.

@alanshaw I totally understand I tried to get some money from PayPal to sponsor this project but it didn’t work out 😞 I am hoping to be able to build something with @wzrdtales and others and eventually merge back to this project

**Comment by gabrielcsapo** [comment]
@wzrdtales @alanshaw http://www.gabrielcsapo.com/starbuck/ got something working over the weekend. Gitlab and Github support out of the box, needs some love, but I think we can really make something different. @alanshaw I borrowed some functions from david and your work on all of this really helped me shape the direction I wanted to go in. 

Here's to hoping that one day starbuck and david can become one again!

**Pull request closed without merging**
