### PR TITLE
support non-root package.json #160

### PR DESCRIPTION
**Pull request by caktux**

### CODE REVIEW

**Comment by mnquintana** [comment]
@alanshaw Just a friendly ping to take a look at this when you get the chance - it would be so so awesome to have #160 implemented. :smile:

**Comment by floydpink** [comment]
+1

**Comment by alanshaw** [comment]
Hey! Thanks so much for the time you've spent implementing this. Sorry I haven't got round to looking at it till now.

I think it might be better to specify the path in the URL rather than the querystring.

Something like this:
https://david-dm.org/[user]/[repo]/[branch]/[path]

What do you think?

Also, `manifest.js` emits events about what dependencies have changed. I can see a potential problem where there is more than one package.json in a repo - any listeners won't know which one it's referring to.

**Comment by caktux** [comment]
Specifying the path in the URL could get ugly and block features from being added later on, since any path more that a single level deep will also include a slash. I think the querystring is the best option here.

I haven't looked into events and listeners, but since path is passed to `getManifest`, might just need to pass it to events that need it also?

**Comment by lijunle** [comment]
+1

**Pull request merged**
