### PR TITLE
adding docker support

### PR DESCRIPTION
**Pull request by ekristen**
Adds docker support

You can set this up as a trusted build with https://hub.docker.com

### CODE REVIEW

**Comment by alanshaw** [comment]
Thanks @ekristen this looks great! Could you add some documentation to the README.md to explain that it now has docker support and how to get it up and running using docker?

**Comment by alanshaw** [comment]
*bump*

I'd love to get this in, just needs a little documentation!

**Comment by yannickglt** [comment]
:+1:

**Comment by ekristen** [comment]
I'm all for getting this updated. Would you be opposed to merging in the RC config one too? or is that too much of a change. The reason I ask is because the RC config would make configuring David WWW 100% by env vars possible which makes the configuration and documentation to for docker easier.  

Without it, its a bit more work, but not impossible.

**Comment by alanshaw** [comment]
Yes I'd rather use rc

**Comment by ekristen** [comment]
should I merge my RC PR into this one, so its all in one fell swoop?

**Comment by alanshaw** [comment]
if you like yeah...

**Comment by ekristen** [comment]
Superseded by https://github.com/alanshaw/david-www/pull/220

**Pull request closed without merging**
