### PR TITLE
Implement support to get dependencies of branch/tags/commits

### LINKED ISSUE #29: View dependency status for branch/tag
David currently only looks at master. Allow view status page and get badge for branch or tree.

### PR DESCRIPTION
**Pull request by aivus**
Fix #29

### CODE REVIEW

**Comment by ilanbiala** [comment]
This would be awesome, because a lot of times I update dependencies in my develop branch and every so often merge into master.

**Comment by creynders** [comment]
:+1:

**Comment by ilanbiala** [comment]
@aivus can you rebase this off the newest changes in master?

**Comment by aivus** [comment]
I'll rebase it ASAP

**Comment by aivus** [comment]
Fix behavior with default brabch and change caching for use branches.

**Comment by alanshaw** [comment]
Thanks @aivus I'll take a look as soon as I can :thumbsup:

**Comment by danielgtaylor** [comment]
LGTM :+1:

**Comment by aivus** [comment]
ping @alanshaw

**Comment by alanshaw** [comment]
Thanks, this is awesome!

**Pull request merged**
